import type { Metadata } from "next";
import { NavBar } from "@/components/NavBar";
import { Footer } from "@/components/footer";
import "./globals.css";


export const metadata: Metadata = {
  title: "jayac",
  description: "Generated by create next app",
  authors: [{name: "anish chhitu"}],
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className="w-full dark:bg-black select-none bg-slate-100 flex flex-col items-center min-h-screen">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
